import { FormEvent, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { ArrowDown, BookOpen, Heart, Leaf, MapPin, Search, Users, X, LogIn, LogOut, Pencil, Save, UserPlus } from 'lucide-react'
import type { User } from '@supabase/supabase-js'
import { supabase } from './supabase'

type Member = { id: string; family_id: string; user_id: string|null; full_name: string; parent_id: string|null; birth_year: number|null; death_year: number|null; birthplace: string|null; bio: string|null; gender: string|null }
const familyId='10000000-0000-4000-8000-000000000001'
const sample: Member[] = [
 {id:'mat-isa',family_id:familyId,user_id:null,full_name:'Mat Isa',parent_id:null,birth_year:null,death_year:null,birthplace:null,bio:'Pangkal salasilah keluarga ini. Kisah dan butiran beliau boleh dilengkapkan oleh keluarga.',gender:'Lelaki'},
 {id:'mat-deah',family_id:familyId,user_id:null,full_name:'Mat Deah',parent_id:'mat-isa',birth_year:null,death_year:null,birthplace:null,bio:'Anak kepada Mat Isa.',gender:'Tidak diketahui'},
 {id:'tok-awang',family_id:familyId,user_id:null,full_name:'Tok Awang',parent_id:'mat-isa',birth_year:null,death_year:null,birthplace:null,bio:'Anak kepada Mat Isa.',gender:'Lelaki'},
 {id:'tok-sabah',family_id:familyId,user_id:null,full_name:"Tok Sa'bah",parent_id:'mat-isa',birth_year:null,death_year:null,birthplace:null,bio:'Anak kepada Mat Isa.',gender:'Perempuan'}]
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()

function branchMatches(member:Member,members:Member[],query:string,seen=new Set<string>()):boolean{
 if(seen.has(member.id))return false
 if(!query||member.full_name.toLowerCase().includes(query.toLowerCase()))return true
 const next=new Set(seen);next.add(member.id)
 return members.some(child=>child.parent_id===member.id&&branchMatches(child,members,query,next))
}
function branchDepth(member:Member,members:Member[],seen=new Set<string>()):number{
 if(seen.has(member.id))return 0
 const next=new Set(seen);next.add(member.id)
 const children=members.filter(child=>child.parent_id===member.id)
 return 1+Math.max(0,...children.map(child=>branchDepth(child,members,next)))
}
function reachableMembers(member:Member,members:Member[],seen=new Set<string>()):Set<string>{
 if(seen.has(member.id))return seen
 seen.add(member.id)
 members.filter(child=>child.parent_id===member.id).forEach(child=>reachableMembers(child,members,seen))
 return seen
}

function App(){
 const [members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState<Member|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[dbError,setDbError]=useState(false)
 const [user,setUser]=useState<User|null>(null),[admin,setAdmin]=useState(false),[authOpen,setAuthOpen]=useState(false),[passwordSetup,setPasswordSetup]=useState(false),[edit,setEdit]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[inviteMember,setInviteMember]=useState(''),[inviteEmail,setInviteEmail]=useState('')
 useEffect(()=>{if(!supabase)return; if(/type=(invite|recovery)/.test(window.location.hash))setPasswordSetup(true);supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null)); const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{setUser(s?.user??null);if(event==='PASSWORD_RECOVERY'||(/type=(invite|recovery)/.test(window.location.hash)&&!!s))setPasswordSetup(true)}); return()=>subscription.unsubscribe()},[])
 useEffect(()=>{let alive=true;async function load(){if(!supabase){if(alive){setMembers(sample);setLoading(false)}return};const [{data,error},{data:links,error:linkError}]=await Promise.all([supabase.from('family_members').select('id,family_id,user_id,full_name,birth_year,death_year,birthplace,bio,gender').eq('family_id',familyId).order('created_at'),supabase.from('family_relationships').select('member_id,related_member_id,relationship_type').eq('family_id',familyId).eq('relationship_type','parent')]);if(!alive)return;if(error||linkError){setDbError(true);setMembers(sample)}else setMembers((data??[]).map((m:any)=>({...m,parent_id:links?.find((r:any)=>r.member_id===m.id)?.related_member_id??null})));setLoading(false)}void load();return()=>{alive=false}},[])
 useEffect(()=>{async function check(){if(!supabase||!user){setAdmin(false);return};const {data}=await supabase.from('family_admins').select('family_id').eq('family_id',familyId).eq('user_id',user.id).maybeSingle();setAdmin(!!data)}void check()},[user])
 const myProfile=members.find(m=>m.user_id===user?.id)??null
 const root=members.find(m=>m.full_name==='Mat Isa')??members[0]??null
 const reachable=root?reachableMembers(root,members):new Set<string>()
 const unlinked=members.filter(m=>!reachable.has(m.id))
 const generationCount=root?branchDepth(root,members):0
 const hasSearchMatch=members.some(m=>m.full_name.toLowerCase().includes(query.toLowerCase()))
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setNotice('');const {error}=await supabase.auth.signInWithPassword({email,password});setNotice(error?.message??'Berjaya log masuk.');setBusy(false);if(!error)setAuthOpen(false)}
 async function setNewPassword(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const form=new FormData(e.currentTarget as HTMLFormElement);const {error}=await supabase.auth.updateUser({password:String(form.get('new_password'))});setNotice(error?.message??'Kata laluan berjaya ditetapkan.');setBusy(false);if(!error){setPasswordSetup(false);window.history.replaceState({},document.title,window.location.pathname)}}
 async function saveProfile(e:FormEvent){e.preventDefault();if(!supabase||!selected)return;setBusy(true);const form=new FormData(e.currentTarget as HTMLFormElement);const patch={full_name:String(form.get('full_name')),birth_year:Number(form.get('birth_year'))||null,death_year:Number(form.get('death_year'))||null,birthplace:String(form.get('birthplace'))||null,bio:String(form.get('bio'))||null,gender:String(form.get('gender'))||null};const {error}=await supabase.from('family_members').update(patch).eq('id',selected.id);if(error)setNotice(error.message);else{setMembers(ms=>ms.map(m=>m.id===selected.id?{...m,...patch}:m));setSelected({...selected,...patch});setEdit(false);setNotice('Profil berjaya dikemas kini.')}setBusy(false)}
 async function addMember(e:FormEvent){e.preventDefault();if(!supabase)return;const form=e.currentTarget as HTMLFormElement;const values=new FormData(form);const parentId=String(values.get('parent_id')||'')||null;setBusy(true);setNotice('');const {data:created,error}=await supabase.from('family_members').insert({family_id:familyId,full_name:String(values.get('full_name')).trim(),birth_year:Number(values.get('birth_year'))||null,death_year:Number(values.get('death_year'))||null,birthplace:String(values.get('birthplace')).trim()||null,gender:String(values.get('gender'))||null,bio:String(values.get('bio')).trim()||null}).select('id,family_id,user_id,full_name,birth_year,death_year,birthplace,bio,gender').single();if(error||!created){setNotice(error?.message??'Ahli keluarga tidak dapat ditambah.');setBusy(false);return}if(parentId){const {error:relationshipError}=await supabase.from('family_relationships').insert({family_id:familyId,member_id:created.id,related_member_id:parentId,relationship_type:'parent'});if(relationshipError){await supabase.from('family_members').delete().eq('id',created.id);setNotice(`Ahli tidak ditambah kerana hubungan ibu/bapa gagal disimpan: ${relationshipError.message}`);setBusy(false);return}}setMembers(ms=>[...ms,{...created,parent_id:parentId}]);form.reset();setNotice('Ahli keluarga berjaya ditambah.');setBusy(false)}
 async function invite(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setNotice('');const {data:{session}}=await supabase.auth.getSession();const response=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/invite-member`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`,'apikey':import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({member_id:inviteMember,email:inviteEmail})});const result=await response.json();setNotice(response.ok?'Jemputan dihantar melalui e-mel.':(result.error??'Jemputan gagal.'));setBusy(false)}
 return <main className="page-shell">
 <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Leaf size={19}/></span><span>Salasilah<span className="brand-light">Keluarga</span></span></a><nav><a href="#salasilah" className="active">Salasilah</a><a href="#tentang">Tentang</a></nav><button className="top-action" onClick={()=>user?void supabase?.auth.signOut():setAuthOpen(true)}>{user?<><LogOut size={16}/> Log keluar</>:<><LogIn size={16}/> Log masuk</>}</button><button className="top-action" onClick={()=>root&&setSelected(root)}>Lihat pangkal keluarga <ArrowDown size={15}/></button></header>
 <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span/> CERITA KELUARGA KITA</div><h1>Setiap nama,<br/><em>ada ceritanya.</em></h1><p>Jejak asal usul keluarga, kenali ikatan yang menghubungkan kita, dan simpan cerita untuk generasi seterusnya.</p><a href="#salasilah" className="primary-button">Teroka salasilah <ArrowDown size={16}/></a><div className="hero-note"><span className="note-avatars"><i>M</i><i>D</i><i>A</i></span><span>Salasilah keluarga <b>Mat Isa</b></span></div></div><div className="hero-art"><div className="art-halo"></div><div className="art-line line-a"></div><div className="art-line line-b"></div><div className="art-line line-c"></div><div className="art-center"><Leaf size={36}/><small>AKAR KELUARGA</small></div><div className="art-tag tag-one">Mat Isa</div><div className="art-tag tag-two">Mat Deah</div><div className="art-tag tag-three">Tok Awang</div><div className="art-tag tag-four">Tok Sa'bah</div><span className="art-dot dot-one"/><span className="art-dot dot-two"/><span className="art-dot dot-three"/><span className="art-dot dot-four"/><div className="art-caption">Ikatan yang merentasi generasi <Heart size={13} fill="currentColor"/></div></div></section>
 <section className="stats"><div><Users size={19}/><span><strong>{members.length}</strong> ahli keluarga</span></div><div><Leaf size={19}/><span><strong>{generationCount}</strong> generasi direkodkan</span></div><div className="stats-note">Dibina daripada ingatan, dikekalkan bersama.</div></section>
 <section className="tree-section" id="salasilah"><div className="section-heading"><div><div className="eyebrow">POHON KELUARGA</div><h2>Salasilah <em>Mat Isa</em></h2><p>Setiap cabang membawa kisah tersendiri.</p></div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama..." aria-label="Cari ahli keluarga"/>{query&&<button onClick={()=>setQuery('')} aria-label="Padam carian"><X size={14}/></button>}</label></div>
 {dbError&&<div className="notice">Data contoh dipaparkan. Semak konfigurasi Supabase dan SQL persediaan.</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {loading?<div className="empty">Memuatkan salasilah…</div>:!hasSearchMatch?<div className="empty">Tiada nama ditemui.</div>:<div className="tree"><div className="generation-label"><span>POHON KELUARGA</span><i/></div>{root&&branchMatches(root,members,query)&&<div className="family-tree-root"><FamilyBranch member={root} members={members} query={query} root onSelect={setSelected}/></div>}{unlinked.some(m=>branchMatches(m,members,query))&&<div className="unlinked-group"><div className="generation-label"><span>AHLI BELUM DIHUBUNGKAN</span><i/></div><div className="unlinked-members">{unlinked.filter(m=>branchMatches(m,members,query)).map(member=><MemberCard key={member.id} member={member} onClick={()=>setSelected(member)}/>)}</div></div>}</div>}
 <div className="tree-foot"><BookOpen size={16}/> <span>Salasilah ini berkembang bersama cerita keluarga.</span></div></section>
 {admin&&<section className="tree-section"><div className="section-heading"><div><div className="eyebrow">PENGURUS KELUARGA</div><h2>Urus ahli keluarga</h2><p>Tambah profil ahli dan jemput mereka menggunakan akaun e-mel.</p></div></div><div className="admin-form-heading"><h3>Tambah ahli keluarga</h3><p>Maklumat e-mel tidak diperlukan untuk menambah profil.</p></div><form className="member-form" onSubmit={addMember}><input required name="full_name" placeholder="Nama penuh"/><select name="parent_id" defaultValue=""><option value="">Pilih ibu atau bapa (pilihan)</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><input name="birth_year" type="number" min="0" max="2100" placeholder="Tahun lahir (pilihan)"/><input name="death_year" type="number" min="0" max="2100" placeholder="Tahun meninggal (pilihan)"/><input name="birthplace" placeholder="Tempat asal (pilihan)"/><select name="gender" defaultValue=""><option value="">Jantina (pilihan)</option><option value="Lelaki">Lelaki</option><option value="Perempuan">Perempuan</option><option value="Tidak diketahui">Tidak diketahui</option></select><textarea className="member-bio" name="bio" placeholder="Cerita ringkas (pilihan)"/><button className="primary-button" disabled={busy}><UserPlus size={15}/> Tambah ahli</button></form><div className="admin-form-heading invite-heading"><h3>Jemput ahli log masuk</h3><p>Pilih profil yang telah wujud dan hantar pautan untuk menetapkan kata laluan.</p></div><form className="invite-form" onSubmit={invite}><select required value={inviteMember} onChange={e=>setInviteMember(e.target.value)}><option value="">Pilih profil ahli</option>{members.filter(m=>!m.user_id).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><input required type="email" placeholder="E-mel ahli" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><button className="primary-button" disabled={busy}>Hantar jemputan</button></form></section>}
 <section className="quote" id="tentang"><span className="quote-mark">“</span><p>Akar yang kita kenali memberi kita tempat untuk bertumbuh.</p><span className="quote-caption">MENYIMPAN CERITA, MENGHUBUNGKAN GENERASI</span><Leaf className="quote-leaf" size={50}/></section><footer><a className="brand" href="#top"><span className="brand-mark"><Leaf size={17}/></span><span>Salasilah<span className="brand-light">Keluarga</span></span></a><span>Warisan keluarga, untuk generasi akan datang.</span><span>V0.2 · Mat Isa</span></footer>
 {passwordSetup&&<div className="modal-backdrop"><section className="profile-modal" role="dialog" aria-modal="true" aria-label="Tetapkan kata laluan"><div className="profile-avatar"><Leaf/></div><span className="eyebrow">AKAUN AHLI KELUARGA</span><h2>Tetapkan kata laluan</h2><p className="profile-bio">Pautan jemputan berjaya dibuka. Pilih kata laluan baharu untuk akaun anda.</p><form className="auth-form" onSubmit={setNewPassword}><input required name="new_password" type="password" minLength={8} autoComplete="new-password" placeholder="Kata laluan baharu (min 8 aksara)"/><button className="primary-button" disabled={busy}><Save size={15}/> Simpan kata laluan</button></form></section></div>}
 {authOpen&&<div className="modal-backdrop" onClick={()=>setAuthOpen(false)}><section className="profile-modal" role="dialog" aria-modal="true" aria-label="Log masuk" onClick={e=>e.stopPropagation()}><button className="close-button" onClick={()=>setAuthOpen(false)} aria-label="Tutup"><X/></button><span className="eyebrow">AHLI KELUARGA</span><h2>Log masuk</h2><p className="profile-bio">Akaun keluarga dibuat melalui jemputan pentadbir.</p><form className="auth-form" onSubmit={signIn}><input required type="email" autoComplete="email" placeholder="Alamat e-mel" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength={8} type="password" autoComplete="current-password" placeholder="Kata laluan" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary-button" disabled={busy}>Log masuk</button></form></section></div>}
 {selected&&<div className="modal-backdrop" onClick={()=>{setSelected(null);setEdit(false)}}><section className="profile-modal" role="dialog" aria-modal="true" aria-label={`Profil ${selected.full_name}`} onClick={e=>e.stopPropagation()}><button className="close-button" onClick={()=>{setSelected(null);setEdit(false)}} aria-label="Tutup"><X/></button><div className="profile-avatar">{initials(selected.full_name)}</div><span className="eyebrow">PROFIL AHLI KELUARGA</span>{edit?<form className="auth-form" onSubmit={saveProfile}><input name="full_name" required defaultValue={selected.full_name} placeholder="Nama penuh"/><input name="birth_year" type="number" defaultValue={selected.birth_year??''} placeholder="Tahun lahir"/><input name="death_year" type="number" defaultValue={selected.death_year??''} placeholder="Tahun meninggal"/><input name="birthplace" defaultValue={selected.birthplace??''} placeholder="Tempat asal"/><input name="gender" defaultValue={selected.gender??''} placeholder="Jantina"/><textarea name="bio" defaultValue={selected.bio??''} placeholder="Cerita ringkas"/><button className="primary-button" disabled={busy}><Save size={15}/> Simpan</button></form>:<><h2>{selected.full_name}</h2><div className="profile-rel">{selected.parent_id?`Anak kepada ${members.find(m=>m.id===selected.parent_id)?.full_name??'ahli keluarga'}`:'Pangkal salasilah'}</div><div className="profile-facts">{selected.birth_year&&<div><span>Tahun lahir</span><b>{selected.birth_year}</b></div>}{selected.death_year&&<div><span>Tahun meninggal</span><b>{selected.death_year}</b></div>}{selected.gender&&<div><span>Jantina</span><b>{selected.gender}</b></div>}{selected.birthplace&&<div><span>Tempat asal</span><b><MapPin size={14}/>{selected.birthplace}</b></div>}</div><p className="profile-bio">{selected.bio||'Belum ada cerita direkodkan untuk ahli keluarga ini.'}</p><div className="profile-note"><Heart size={15}/> Cerita keluarga disimpan bersama.</div>{(selected.user_id===user?.id||admin)&&<button className="edit-profile" onClick={()=>setEdit(true)}><Pencil size={15}/> Edit profil</button>}</>}</section></div>}
 </main>
}
function MemberCard({member,root=false,onClick}:{member:Member;root?:boolean;onClick:()=>void}){return <button className={`member-card ${root?'root-card':''}`} onClick={onClick}><span className="member-avatar">{initials(member.full_name)}</span><span className="member-info"><small>{root?'PANGKAL KELUARGA':'AHLI KELUARGA'}</small><strong>{member.full_name}</strong><span>{root?'Buka profil':'Lihat profil'} <span aria-hidden>↗</span></span></span><span className="member-leaf"><Leaf size={16}/></span></button>}
function FamilyBranch({member,members,query,onSelect,root=false,ancestors=[]}:{member:Member;members:Member[];query:string;onSelect:(member:Member)=>void;root?:boolean;ancestors?:string[]}){
 const childrenRef=useRef<HTMLDivElement>(null)
 const [connectors,setConnectors]=useState<{width:number;height:number;path:string}|null>(null)
 const children=members.filter(child=>child.parent_id===member.id&&!ancestors.includes(child.id)&&branchMatches(child,members,query))
 useLayoutEffect(()=>{
  const container=childrenRef.current
  if(!container||children.length===0)return
  const update=()=>{
   const bounds=container.getBoundingClientRect()
   const cards=Array.from(container.querySelectorAll<HTMLElement>(':scope > .family-branch > .member-card'))
   const points=cards.map(card=>{const rect=card.getBoundingClientRect();return{x:rect.left+rect.width/2-bounds.left,y:rect.top-bounds.top}})
   if(!points.length)return
   const busY=12
   const path=`M ${points[0].x} ${busY} H ${points[points.length-1].x} ${points.map(point=>`M ${point.x} ${busY} V ${point.y}`).join(' ')}`
   setConnectors({width:bounds.width,height:Math.max(32,...points.map(point=>point.y+2)),path})
  }
  update()
  const observer=new ResizeObserver(update)
  observer.observe(container)
  container.querySelectorAll(':scope > .family-branch > .member-card').forEach(card=>observer.observe(card))
 window.addEventListener('resize',update)
  return()=>{observer.disconnect();window.removeEventListener('resize',update)}
 },[children.length,query])
 if(ancestors.includes(member.id)||!branchMatches(member,members,query))return null
 return <div className={`family-branch${root?' root-branch':''}`}><MemberCard member={member} root={root} onClick={()=>onSelect(member)}/>{children.length>0&&<div className="family-children" ref={childrenRef}>{connectors&&<svg className="family-connectors" width={connectors.width} height={connectors.height} viewBox={`0 0 ${connectors.width} ${connectors.height}`} aria-hidden="true"><path d={connectors.path}/></svg>}{children.map(child=><FamilyBranch key={child.id} member={child} members={members} query={query} onSelect={onSelect} ancestors={[...ancestors,member.id]}/>)}</div>}</div>
}
export default App
